title: Alan Bertani
email: alanbertani0x01@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Blockchain and Cybersecurity
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
avatar: ./FRSEIadXEAEnaS8.jpg
# Build settings
plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton

social:
  name: Alan Bertani
  links:
    - https://github.com/alk0x1
    - https://twitter.com/alk0x1

lang: en